## Category [/category/{id}]
### Delete a Category [DELETE]
+ Request
    + Header

            Authorization: JWT "JWT_TOKEN_HERE"

    + Parameters

        + id (string)
        + action (string) - move / delete Move to default category if not specified
        + destination (string) - New category id

+ Response 204
        {
            "action": "move",
            "destination": 103,
            "affected_post_count": 13
        } 

### Update a Category [PUT]
+ Request
    + Header

            Authorization: JWT "JWT_TOKEN_HERE"

    + Parameters

        + id (string)
        + name (string)

+ Response (application/json)

        {
            "id": 1,
            "name": 123
        }
