## Post [/post/{id}]
### Retrive Post [GET]
+ Parameters
    + id (string)

+ Response (application/json)

    {
        "id": 1,
        "category_id": 1,
        "category": "Hello",
        "title": "Lorem Ipsum",
        "author": "Miriam",
        "updated_at": "2018-03-29 19:56:00",
        "revision_id": 101,
        "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
    }

### Update Post [PUT]
+ Request
    + Header

        Authorization: JWT "JWT_TOKEN_HERE"

    + Parameters
        + id (string)
        + category_id (integer)
        + title (string)
        + contents (string)

+ Response (application/json)

    {
        "id": 1,
        "category_id": 1,
        "category": "Hello",
        "title": "Lorem Ipsum New",
        "author": "Miriam",
        "updated_at": "2018-03-29 19:57:00",
        "revision_id": 102,
        "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
    }

### Delete Post [DELETE]
Move post into recycle bin

+ Request
    + Header

        Authorization: JWT "JWT_TOKEN_HERE"

+ Response 204

## Posts Collection [/posts]
### List all posts [GET]
+ Parameters
    + filter (string) - Filter by author / category
    + id (string) - Author (user_id) / category
    + page (string) 10 posts per page

+ Response (application/json)

    {
        "page": 1,
        "filter_by": "author",
        "posts": [
            {
                "id": 1,
                "category_id": 1,
                "category": "Hello",
                "title": "Lorem Ipsum",
                "author": "Miriam",
                "user_id": 2,
                "updated_at": "2018-03-29 19:58:00",
                "revision_id": 103
            }
            ...
        ]
    }

## Create Post [POST]
+ Request
    + Header

        Authorization: JWT "JWT_TOKEN_HERE"

    + Parameters
        + id (string)
        + category_id (integer)
        + title (string)
        + contents (string)

+ Response (application/json)
    {
        "id": 1,
        "category_id": 1,
        "category": "Hello",
        "title": "Lorem Ipsum New",
        "author": "Miriam",
        "updated_at": "2018-03-29 19:57:00",
        "revision_id": 102,
        "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
    }

## Revision [/revision/{revision_id}]
### Retrive Revision [GET]
+ Parameters
    + revision_id (string)

+ Response (application/json)
    {
        "id": 100,
        "post_id": 1,
        "updated_at": "2018-03-11 18:56:00",
        "content": "Hello Typist!"
    }

### Delete Revision [DELETE]
+ Parameters
    + revision_id

+ Response 204

## Revision Collection [/post/{post_id}/revision]
### List All Revision of a Post [GET]
+ Request
    + Header

        + Authorization: JWT "JWT_TOKEN_HERE"
    + Parameters

        + post_id (string)

+ Response (application/json)
    [
        {
            "id": 100,
            "updated_at": "2018-03-29 17:00:00",
        }
        ...
    ]

### Delete All Revision of a Post [DELETE]
+ Parameters
    + post_id (string)

+ Response 204

### Create a Revision [POST]
+ Request
    + Header
        Authorization: JWT "JWT_TOKEN_HERE"

    + Parameters
        + post_id (string)
        + content (string)

+ Response (application/json)
    {
        "id": 103,
        "post_id": 1,
        "content": "Lorem Ipsum"
    }
