FORMAT: 1A

# Typist API

Typist API allows user to create their CMS easily.

# Group Users

This section groups Typist API user resources.

{{ partial "users.apib" }}

# Group Posts

This section groups Typist API post resources.

{{ partial "posts.apib" }}

# Group Categories

This section groups Typist API category resources.

{{ partial "categories.apib" }}
